using System.Collections;
using UnityEngine;
using UnityEngine.InputSystem;

/// <summary>
/// This script handles the physics-based movement for the player character.
/// It utilises the event-driven Unity Input System to read twin-stick/WASD inputs
/// and applies them to a Rigidbody without relying on inefficient per-frame polling.
/// </summary>

public class PlayerController : MonoBehaviour
{
    [SerializeField] private float _moveSpeed = 5f;

    [Header("Dash Settings")]
    [SerializeField] private float _dashSpeed = 20f;
    [SerializeField] private float _dashDuration = 0.2f;
    [SerializeField] private float _dashCooldown = 1f;
    [SerializeField] private TrailRenderer _dashTrail;

    private bool _isDashing = false;
    private float _nextDashTime = 0f;
    private Vector3 _dashDirection;

    // A public getter for the UI to read the dash cooldown percentage
    // Returns 1 (full) if ready, or a fraction (0.0 to 0.99) if on cooldown
    public float DashCooldownRatio
    {
        get
        {
            if (Time.time >= _nextDashTime) return 1f;  // Ready to dash

            // Calculate the remaining time as a percentage
            float timeRemaining = _nextDashTime - Time.time;
            return 1f - (timeRemaining / _dashCooldown);
        }
    }

    [Header("Aiming Settings")]
    [SerializeField] private Transform _crosshair;         // Drag the crosshair GameObject here in Inspector !!
    [SerializeField] private float _maxAimRadius = 8f;     // Maximum distance the gamepad crosshair can go.
    [SerializeField] private float _crosshairSpeed = 25f;  // How fast the crosshair glides to the JOYSTICK target

    [Header("Ultimate Settings")]
    [SerializeField] private GameObject _bigCheesePrefab;
    [SerializeField] private float _maxUltCharge = 100f;
    [SerializeField] private float _passiveChargeRate = 5f;  // Charges 5 points per second

    private float _currentUltCharge = 0f;

    // Public getter for the UI to read the ultimate charge percentage
    public float UltChargeRatio => _currentUltCharge / _maxUltCharge;
    
    // Stores the raw 2D input (X and Y) from the joystick or WASD keys.
    private Vector2 _inputVector;
    private Vector2 _aimVector;
    private Vector2 _mousePosition;      // Stores the physical screen position of the PC mouse
    private bool _isUsingMouse = false;  // Tracks which device is being used
    // A public "getter" so the UIManager can read this state safely
    public bool IsUsingMouse => _isUsingMouse; 
    
    private Rigidbody _rb;
    private PlayerControls _controls;  // The C# class generated by the Input System.
    private Camera _mainCamera;        // The camera is needed to calculate mouse aiming
    private WeaponSystem _weaponSystem;
    private HealthSystem _healthSystem;
    private bool _isFiring;

    private void Awake()
    {
        InitialiseComponents();
        SubscribeToInputs();
    }

    // -----------------------------------------------------------------------------------------------------------------
    // --- SETUP METHODS ---

    /// <sumary>
    /// Gathers all the required components so Awake() stays clean and readable.
    /// </sumary> 

    private void InitialiseComponents()
    {
        _rb = GetComponent<Rigidbody>();
        _mainCamera = Camera.main;
        _weaponSystem = GetComponent<WeaponSystem>();
        _healthSystem = GetComponent<HealthSystem>();

        // Instantiate this as a new object because it is a generated C# class, not a MonoBehaviour component.
        _controls = new PlayerControls();
    }

    /// <summary>
    /// Acts as a switchboard to connect all the input events
    /// </summary>
    private void SubscribeToInputs()
    {
        SetupMovementInput();
        SetupAimingInput();
        SetupActionInput();
    }

    private void SetupMovementInput()
    {
        // --- MOVEMENT INPUT ---
        /// <summary>
        /// This is the Event-Driven architecture.
        /// '+=' is used to "subscribe" to the Input System's events.
        /// When the Joystick is moved (performed), the system fires an event.
        /// 
        /// 'ctx' means "Context". It is a data package holding all the info about the input
        /// (e.g., how far the joystick is tilted).
        /// The '=>' (lambda) takes that context, reads its Vector2 value, and saves it to _inputVector.
        /// When the stick is released (canceled), the vector is reset to 0 so the player stops.
        /// </summary>
        _controls.Player.Move.performed += ctx => _inputVector = ctx.ReadValue<Vector2>();
        _controls.Player.Move.canceled += ctx => _inputVector = Vector2.zero;
    }

    private void SetupAimingInput()
    {
        // --- GAMEPAD AIMING INPUT ---
        _controls.Player.Aim.performed += ctx =>
        {
            _aimVector = ctx.ReadValue<Vector2>();

            // If the joystick is touched, switch to Gamepad mode AND hide the mouse
            if (_isUsingMouse)
            {
                _isUsingMouse = false;
                Cursor.visible = false;
            }
        };
        _controls.Player.Aim.canceled += ctx => _aimVector = Vector2.zero;

        // --- PC MOUSE AIMING ---
        _controls.Player.MousePosition.performed += ctx =>
        {
            _mousePosition = ctx.ReadValue<Vector2>();

            // If the mouse is moved, switch to PC Mouse mode
            if (!_isUsingMouse)
            {
                _isUsingMouse = true;
                Cursor.visible = true;
            }
        };
    }

    private void SetupActionInput()
    {
        // --- FIRING ---

        // Listen for the Fire button being pressed and released
        _controls.Player.Fire.performed += ctx => _isFiring = true;
        _controls.Player.Fire.canceled += ctx => _isFiring = false;

        // --- RELOADING ---
        _controls.Player.Reload.performed += ctx =>
        {
            if (_weaponSystem != null) _weaponSystem.Reload();
        };

        // --- DASHING ---
        _controls.Player.Dash.performed += ctx => PerformDash();

        // --- ULTIMATE ---
        _controls.Player.Ultimate.performed += ctx => PerformUltimate();

        // --- WEAPON SWAP ---
        // Cycle Forward (R1 / E)
        _controls.Player.NextWeapon.performed += ctx =>
        {
            if (_weaponSystem != null)
            {
                _weaponSystem.CycleWeaponForward();
            }
        };

        // Cycle Backward (L1 / Q)
        _controls.Player.PreviousWeapon.performed += ctx =>
        {
            if (_weaponSystem != null)
            {
                _weaponSystem.CycleWeaponBackward();
            }
        };

        // --- PAUSE ---
        _controls.Player.Pause.performed += ctx =>
        {
            if (UIManager.Instance != null)
            {
                UIManager.Instance.TogglePause();
            }
        };
    }

    // -----------------------------------------------------------------------------------------------------------------

    // --- ON ENABLED AND DISABLED ---
    /// <summary>
    /// The new Input System requires actions to be explicitly turned on and off.
    /// OnEnable runs when the script is turned on, allowing it to listen for button inputs.
    /// OnDisable runs when the script is turned off (like if the player dies or pauses).
    /// Disabling prevents the script from trying to read input that don't exist, preventing memory leaks and crashes.
    /// </summary>

    private void OnEnable()
    {
        _controls.Enable();
    }

    private void OnDisable()
    {
        _controls.Disable();
    }

    // -----------------------------------------------------------------------------------------------------------------

    // --- MOVEMENT ---
    /// <summary>
    /// Movement is handled in the Fixed Update because FixedUpdate runs on a reliable,
    /// fixed timer strictly meant for the Physics engine.
    /// Moving Rigidbodies in the regular Update() loop causes the physics to calculate unevenly,
    /// which leads to screen jittering (noted in TDD).
    /// </summary>

    private void FixedUpdate()
    {
        HandleMovement();
    }

    // --- AIMING ---
    // Goes in standard Update() because it handles visual rotation and UI, which should be frame-perfect.
    private void Update()
    {
        HandleAiming();

        // If the Fire button is held down, tell the Weapon System to fire!
        if (_isFiring && _weaponSystem != null)
        {
            _weaponSystem.FireWeapon();
        }

        // Passively charge the ultimate up to 100
        if (_currentUltCharge < _maxUltCharge)
        {
            _currentUltCharge += Time.deltaTime * _passiveChargeRate;
            _currentUltCharge = Mathf.Min(_currentUltCharge, _maxUltCharge);  // Clamp this so it doesn't exceed 100
        }
    }

    private void HandleMovement()
    {
        if (_isDashing)
        {
            // --- DASH MOVEMENT ---
            // Move very fast in the locked dash direction, ignoring the joystick temporarily
            _rb.MovePosition(_rb.position + _dashDirection * _dashSpeed * Time.fixedDeltaTime);
        }
        else
        {
            // --- STANDARD MOVEMENT ---
            // Convert the 2D input (X, Y) into 3D movement (X, 0, Z)
            Vector3 movement = new Vector3(_inputVector.x, 0f, _inputVector.y);

            // --- MOVING THE RIGIDBODY ---
            /// <summary>
            /// Time.fixedDeltaTime is used because it ensures the movement speed is entirely independent
            /// of the frame rate.
            /// Whether the Steam Deck is running at 30 FPS or 60 FPS, the player will cover
            /// the exact same physical distance in the game world per second.
            /// </summary>

            _rb.MovePosition(_rb.position + movement * _moveSpeed * Time.fixedDeltaTime);
        }
    }

    // -----------------------------------------------------------------------------------------------------------------

    // --- AIMING ---
    private void HandleAiming()
    {
        if (_crosshair == null) return;

        if (_isUsingMouse)
        {
            HandleMouseAiming();
        }
        else
        {
            HandleGamepadAiming();
        }
    }

    // --- PC MOUSE AIMING ---
    private void HandleMouseAiming()
    {
        _crosshair.gameObject.SetActive(true);  // Mouse crosshair is always on

        // Create a mathmatical flat plane at the player's feet
        Plane groundPlane = new Plane(Vector3.up, transform.position);

        // Shoot a ray from the camera through the mouse cursor on the screen
        Ray ray = _mainCamera.ScreenPointToRay(_mousePosition);

        // If the ray hits the floor...
        if (groundPlane.Raycast(ray, out float hitDistance))
        {
            // Find the exact 3D point it hit
            Vector3 targetPoint = ray.GetPoint(hitDistance);

            // Smoothly glide the crosshair to the mouse cursor position (helps if frame rates fluctuate)
            Vector3 desiredCrosshairPos = new Vector3(targetPoint.x, transform.position.y + 0.1f, targetPoint.z);
            _crosshair.position = Vector3.Lerp(_crosshair.position, desiredCrosshairPos, Time.deltaTime * _crosshairSpeed);

            // Rotate the player to face the crosshair
            Vector3 aimDirection = (targetPoint - transform.position).normalized;
            aimDirection.y = 0f;  // Keep the mouse from looking up/down

            if (aimDirection.sqrMagnitude > 0.01f)
            {
                Quaternion targetRotation = Quaternion.LookRotation(aimDirection);
                _rb.MoveRotation(Quaternion.Slerp(_rb.rotation, targetRotation, Time.deltaTime * 15f));
            }
        }
    }

    private void HandleGamepadAiming()
    {
        /// --- GAMEPAD AIMING ---
        // DEADZONE CHECK: Only calculate aim if the player is actually pushing the right stick
        if (_aimVector.sqrMagnitude > 0.01f)
        {
            _crosshair.gameObject.SetActive(true);

            // Convert the 2D joystick input into a 3D direction
            Vector3 aimDirection = new Vector3(_aimVector.x, 0f, _aimVector.y).normalized;

            // Let the crosshair move freely
            // Multiply the max radius by the joystick's magnitude
            float currentRadius = _maxAimRadius * _aimVector.magnitude;

            // Calculate exactly where the crosshair wants to be
            Vector3 targetCrosshairPos = transform.position + (aimDirection * currentRadius) + (Vector3.up * 0.1f);

            // Smoothly LERP the crosshair to that target position to eliminate hardware jitter/snapping
            _crosshair.position = Vector3.Lerp(_crosshair.position, targetCrosshairPos, Time.deltaTime * _crosshairSpeed);

            // Rotate the player to face the crosshair
            Quaternion targetRotation = Quaternion.LookRotation(aimDirection);
            _rb.MoveRotation(Quaternion.Slerp(_rb.rotation, targetRotation, Time.deltaTime * 15f));
        }
        else if (_crosshair != null)
        {
            // Hide the crosshair if they let go of the right stick
            _crosshair.gameObject.SetActive(false);
        }
    }

    // === DASHING ===
    private void PerformDash()
    {
        // Only dash if the cooldown is ready and not already dashing
        if (Time.time >= _nextDashTime && !_isDashing)
        {
            // Find out which way the player is currently pushing the movement stick/keys
            _dashDirection = new Vector3(_inputVector.x, 0f, _inputVector.y).normalized;

            // If no movement, dash in the direction the capsule is facing
            if (_dashDirection == Vector3.zero)
            {
                _dashDirection = transform.forward;
            }

            // Set the cooldown and start the dash
            _nextDashTime = Time.time + _dashCooldown;
            StartCoroutine(DashRoutine());
        }
    }

    private IEnumerator DashRoutine()
    {
        _isDashing = true;  // Turn on dash mode

        // Turn on I-Frames
        if (_healthSystem != null)
        {
            _healthSystem.SetInvincible(true);
        }

        // Turn on the trail
        if (_dashTrail != null) _dashTrail.emitting = true;

        // Wait for a fraction of a second while the FixedUpdate handles the high-speed movement
        yield return new WaitForSeconds(_dashDuration);

        // Turn trail off
        if (_dashTrail != null) _dashTrail.emitting = false;

        // Turn I-Frames off
        if (_healthSystem != null)
        {
            _healthSystem.SetInvincible(false);
        }

        _isDashing = false;  // Turn off dash mode and return to normal movement
    }

    // --- ULTIMATE ABILITY ---
    private void PerformUltimate()
    {
        // Only fire if the meter is full
        if (_currentUltCharge >= _maxUltCharge && _bigCheesePrefab != null && _crosshair != null)
        {
            // Calculate a spot 20 units straight up into the air above the crosshair
            Vector3 dropPosition = new Vector3(_crosshair.position.x, 20f, _crosshair.position.z);

            // Spawn the cheese
            Instantiate(_bigCheesePrefab, dropPosition, Quaternion.identity);

            // Reset the meter
            _currentUltCharge = 0f;

            Debug.Log("ULTIMATE USED!");
        }
    }

    // === DEBUGGING ===

    // --- Crosshair Radius --- 
    /// <summary>
    /// This draws a yellow circle in the Unity Editor scene view so you can
    /// easily see and adjust the maximum aiming radius without having to play the game.
    /// </summary>
    private void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.yellow;
        // Draws a wire sphere at the player's position using the max radius
        Gizmos.DrawWireSphere(transform.position, _maxAimRadius);
    }
}
