using UnityEngine;
using UnityEngine.InputSystem;

/// <summary>
/// This script handles the physics-based movement for the player character.
/// It utilises the event-driven Unity Input System to read twin-stick/WASD inputs
/// and applied them to a Rigidbody without relying on inefficient per-frame polling.
/// </summary>

public class PlayerController : MonoBehaviour
{
    [SerializeField] private float _moveSpeed = 5f; 
    
    // Stores the raw 2D input (X and Y) from the joystick or WASD keys.
    private Vector2 _inputVector;                   
    private Rigidbody _rb;
    private PlayerControls _controls;  // The C# class generated by the Input System.

    private void Awake()
    {
        _rb = GetComponent<Rigidbody>();

        // Instantiate this as a new object because it is a generated C# class, not a MonoBehaviour component.
        _controls = new PlayerControls();

        // --- USE THE MOVE ACTION ---
        /// <summary>
        /// This is the Event-Driven architecture in action!
        /// '+=' is used to "subscribe" to the Input System's events.
        /// When the Joystick is moved (performed), the system fires an event.
        /// 
        /// 'ctx' means "Context". It is a data package holding all the info about the input
        /// (e.g., how far the joystick is tilted).
        /// The '=>' (lambda) takes that context, reads its Vector2 value, and saves it to _inputVector.
        /// When the stick is released (canceled), the vector is reset to 0 so the player stops.
        /// </summary>
        _controls.Player.Move.performed += ctx => _inputVector = ctx.ReadValue<Vector2>();
        _controls.Player.Move.canceled += ctx => _inputVector = Vector2.zero;
    }

    // -----------------------------------------------------------------------------------------------------------------

    // --- ON ENABLED AND DISABLED ---
    /// <summary>
    /// The new Input System requires actions to be explicitly turned on and off.
    /// OnEnable runs when the script is turned on, allowing it to listen for button inputs.
    /// OnDisable runs when the script is turned off (like if the player dies or pauses).
    /// Disabling prevents the script from trying to read input that don't exist, preventing memory leaks and crashes.
    /// </summary>

    private void OnEnable()
    {
        _controls.Enable();
    }

    private void OnDisable()
    {
        _controls.Disable();
    }

    // -----------------------------------------------------------------------------------------------------------------

    // --- MOVEMENT ---
    /// <summary>
    /// Movement is handled in the Fixed Update because FixedUpdate runs on a reliable,
    /// fixed timer strictly meant for the Physics engine.
    /// Moving Rigidbodies in the regular Update() loop causes the physics to calculate unevenly,
    /// which leads to screen jittering (noted in TDD).
    /// </summary>

    private void FixedUpdate()
    {
        HandleMovement();
    }

    private void HandleMovement()
    {
        // Convert the 2D input (X, Y) into 3D movement (X, 0, Z)
        Vector3 movement = new Vector3(_inputVector.x, 0f, _inputVector.y);

        // --- MOVING THE RIGIDBODY ---
        /// <summary>
        /// Time.fixedDeltaTime is used because it ensures the movement speed is entirely independent
        /// of the frame rate.
        /// Whether the Steam Deck is running at 30 FPS or 60 FPS, the player will cover
        /// the exact same physical distance in the game world per second.
        /// </summary>

        _rb.MovePosition(_rb.position + movement *  _moveSpeed * Time.fixedDeltaTime);
    }
}
