using UnityEngine;
using UnityEngine.InputSystem;

/// <summary>
/// This script handles the physics-based movement for the player character.
/// It utilises the event-driven Unity Input System to read twin-stick/WASD inputs
/// and applied them to a Rigidbody without relying on inefficient per-frame polling.
/// </summary>

public class PlayerController : MonoBehaviour
{
    [SerializeField] private float _moveSpeed = 5f;

    [Header("Aiming Settings")]
    [SerializeField] private Transform _crosshair;         // Drag the crosshair GameObject here in Inspector !!
    [SerializeField] private float _maxAimRadius = 8f;     // Maximum distance the gamepad crosshair can go.
    [SerializeField] private float _crosshairSpeed = 25f;  // How fast the crosshair glides to the JOYSTICK target
    
    // Stores the raw 2D input (X and Y) from the joystick or WASD keys.
    private Vector2 _inputVector;
    private Vector2 _aimVector;
    private Vector2 _mousePosition;     // Stores the physical screen position of the PC mouse
    private bool _isUsingMouse = false;  // Tracks which device is being used
    
    private Rigidbody _rb;
    private PlayerControls _controls;  // The C# class generated by the Input System.
    private Camera _mainCamera;        // The camera is needed to calculate mouse aiming

    private void Awake()
    {
        _rb = GetComponent<Rigidbody>();
        _mainCamera = Camera.main;

        // Instantiate this as a new object because it is a generated C# class, not a MonoBehaviour component.
        _controls = new PlayerControls();

        // --- MOVEMENT INPUT ---
        /// <summary>
        /// This is the Event-Driven architecture in action!
        /// '+=' is used to "subscribe" to the Input System's events.
        /// When the Joystick is moved (performed), the system fires an event.
        /// 
        /// 'ctx' means "Context". It is a data package holding all the info about the input
        /// (e.g., how far the joystick is tilted).
        /// The '=>' (lambda) takes that context, reads its Vector2 value, and saves it to _inputVector.
        /// When the stick is released (canceled), the vector is reset to 0 so the player stops.
        /// </summary>
        _controls.Player.Move.performed += ctx => _inputVector = ctx.ReadValue<Vector2>();
        _controls.Player.Move.canceled += ctx => _inputVector = Vector2.zero;

        // -----------------------------------------------------------------------------------------------

        // --- GAMEPAD AIMING INPUT ---
        _controls.Player.Aim.performed += ctx =>
        {
            _aimVector = ctx.ReadValue<Vector2>();
            _isUsingMouse = false;  // If the joystick is touched, switch to Gamepad mode
        };
        _controls.Player.Aim.canceled += ctx => _aimVector = Vector2.zero;

        // --- PC MOUSE AIMING ---
        _controls.Player.MousePosition.performed += ctx =>
        { 
            _mousePosition = ctx.ReadValue<Vector2>();
            _isUsingMouse = true;  // If the mouse is moved, switch to PC Mouse mode
        };
    }

    // -----------------------------------------------------------------------------------------------------------------

    // --- ON ENABLED AND DISABLED ---
    /// <summary>
    /// The new Input System requires actions to be explicitly turned on and off.
    /// OnEnable runs when the script is turned on, allowing it to listen for button inputs.
    /// OnDisable runs when the script is turned off (like if the player dies or pauses).
    /// Disabling prevents the script from trying to read input that don't exist, preventing memory leaks and crashes.
    /// </summary>

    private void OnEnable()
    {
        _controls.Enable();
    }

    private void OnDisable()
    {
        _controls.Disable();
    }

    // -----------------------------------------------------------------------------------------------------------------

    // --- MOVEMENT ---
    /// <summary>
    /// Movement is handled in the Fixed Update because FixedUpdate runs on a reliable,
    /// fixed timer strictly meant for the Physics engine.
    /// Moving Rigidbodies in the regular Update() loop causes the physics to calculate unevenly,
    /// which leads to screen jittering (noted in TDD).
    /// </summary>

    private void FixedUpdate()
    {
        HandleMovement();
    }

    // --- AIMING ---
    // Goes in standard Update() because it handles visual rotation and UI, which should be frame-perfect.
    private void Update()
    {
        HandleAiming();
    }

    private void HandleMovement()
    {
        // Convert the 2D input (X, Y) into 3D movement (X, 0, Z)
        Vector3 movement = new Vector3(_inputVector.x, 0f, _inputVector.y);

        // --- MOVING THE RIGIDBODY ---
        /// <summary>
        /// Time.fixedDeltaTime is used because it ensures the movement speed is entirely independent
        /// of the frame rate.
        /// Whether the Steam Deck is running at 30 FPS or 60 FPS, the player will cover
        /// the exact same physical distance in the game world per second.
        /// </summary>

        _rb.MovePosition(_rb.position + movement *  _moveSpeed * Time.fixedDeltaTime);
    }

    // -----------------------------------------------------------------------------------------------------------------

    // --- AIMING ---
    private void HandleAiming()
    {
        if (_crosshair == null) return;

        if (_isUsingMouse)
        {
            // --- PC MOUSE AIMING ---
            _crosshair.gameObject.SetActive(true);  // Mouse crosshair is always on

            // Create a mathmatical flat plane at the player's feet
            Plane groundPlane = new Plane(Vector3.up, transform.position);

            // Shoot a ray from the camera through the mouse cursor on the screen
            Ray ray = _mainCamera.ScreenPointToRay(_mousePosition);

            // If the ray hits the floor...
            if (groundPlane.Raycast(ray, out float hitDistance))
            {
                // Find the exact 3D point it hit
                Vector3 targetPoint = ray.GetPoint(hitDistance);

                // Smoothly glide the crosshair to the mouse cursor position (helps if frame rates fluctuate)
                Vector3 desiredCrosshairPos = new Vector3(targetPoint.x, transform.position.y + 0.1f, targetPoint.z);
                _crosshair.position = Vector3.Lerp(_crosshair.position, desiredCrosshairPos, Time.deltaTime * _crosshairSpeed);

                // Rotate the player to face the crosshair
                Vector3 aimDirection = (targetPoint - transform.position).normalized;
                aimDirection.y = 0f;  // Keep the mouse from looking up/down

                if (aimDirection.sqrMagnitude > 0.01f)
                {
                    Quaternion targetRotation = Quaternion.LookRotation(aimDirection);
                    _rb.MoveRotation(Quaternion.Slerp(_rb.rotation, targetRotation, Time.deltaTime * 15f));
                }
            }
        }
        else
        {
            /// --- GAMEPAD AIMING ---
            // DEADZONE CHECK: Only calculate aim if the player is actually pushing the right stick
            if (_aimVector.sqrMagnitude > 0.01f)
            {
                _crosshair.gameObject.SetActive(true);

                // Convert the 2D joystick input into a 3D direction
                Vector3 aimDirection = new Vector3(_aimVector.x, 0f, _aimVector.y).normalized;

                // Let the crosshair move freely
                // Multiply the max radius by the joystick's magnitude
                float currentRadius = _maxAimRadius * _aimVector.magnitude;

                // Position = Player Position + Direction * Radius + slight lift so it doesn't clip into the floor
                _crosshair.position = transform.position + (aimDirection * currentRadius) + (Vector3.up * 0.1f);

                // Calculate exactly where the crosshair wants to be
                Vector3 targetCrosshairPos = transform.position + (aimDirection * currentRadius) + (Vector3.up * 0.1f);

                // Smoothly LERP the crosshair to that target position to eliminate hardware jitter/snapping
                _crosshair.position = Vector3.Lerp(_crosshair.position, targetCrosshairPos, Time.deltaTime * _crosshairSpeed);

                // Rotate the player to face the crosshair
                Quaternion targetRotation = Quaternion.LookRotation(aimDirection);
                _rb.MoveRotation(Quaternion.Slerp(_rb.rotation, targetRotation, Time.deltaTime * 15f));
            }
            else if (_crosshair != null)
            {
                // Hide the crosshair if they let go of the right stick
                _crosshair.gameObject.SetActive(false);
            }
        }
    }

    // === DEBUGGING ===

    // --- Crosshair Radius --- 
    /// <summary>
    /// This draws a yellow circle in the Unity Editor scene view so you can
    /// easily see and adjust the maximum aiming radius without having to play the game.
    /// </summary>
    private void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.yellow;
        // Draws a wire sphere at the player's position using the max radius
        Gizmos.DrawWireSphere(transform.position, _maxAimRadius);
    }
}
